name: Upload to CurseForge and Modrinth
on:
  push:
    branches:
      - mc1.20.1/release

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      CURSE_FORGE_API_KEY: ${{ secrets.CURSE_FORGE_API_KEY }}
      MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build jar
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Publish to Modrinth
        run: ./gradlew publishModrinth  --no-configuration-cache

      - name: Publish to CurseForge
        run: ./gradlew publishCurseforge  --no-configuration-cache
